### PR TITLE
Remove space and version specifier from result

### PR DESCRIPTION
**Pull request by wevtimoteo**
There are some projects, such this [one](https://github.com/elixirschool/elixirschool/blob/master/Gemfile), that define ruby version in `Gemfile` with `~> 1.2.3` specifier.

In this PR I've just used `tr` to remove them (and blank chars).

### CODE REVIEW

**Comment by aripollak** [comment]
If a version range is specified in Gemfile, would it be more correct to check Gemfile.lock for the actual locked Ruby version?

**Comment by wevtimoteo** [comment]
@aripollak Nice catch, maybe would be better to check `Gemfile.lock` to identify this pattern:

```
RUBY VERSION
   ruby 2.3.7p456
```

So we'll ensure that is the correct version, but doing that will change all `sed` patterns defined. Maybe we can open an issue for that and for this one I can just implement a test scenario, WDYT?

**Comment by aripollak** [comment]
Hm, I don't think I understand what you're asking. I do think it's time to deprecate Ruby pre-2.1 and Bundler pre-1.13, so the patchlevel and Gemfile can be ignored. By looking at the machine-generated Gemfile.lock instead of Gemfile, I think it will be easier to recognize all bundler-supported scenarios, including version ranges.

**Comment by wevtimoteo** [comment]
> I do think it's time to deprecate Ruby pre-2.1 and Bundler pre-1.13, so the patchlevel and Gemfile can be ignored.

Agreed!

Now about changes: what I mean was to just implement tests scenario for this PR (reading from `Gemfile`) then in a separate PR we can refactor `sed` scripts to identify pattern reading  `Gemfile.lock`. So we can discuss and implement behavior such this one that you described above, WDYT?

**Comment by aripollak** [comment]
I'd prefer not to include these changes as is. It would choose the earliest allowed version of Ruby, which might be counterproductive in some cases since this plugin takes precedence over the per-shell or global version.

**Comment by wevtimoteo** [comment]
No problem, so we can close this one.

**Pull request closed without merging**
